# Generated by Django 5.2.4 on 2025-07-31 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã hồ sơ')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng trị giá')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
            ],
            options={
                'verbose_name': 'Hồ sơ',
                'verbose_name_plural': 'Hồ sơ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='procure/attachments/')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả tài liệu (nếu có)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procure.procurementrecord')),
            ],
            options={
                'verbose_name': 'Tài liệu đính kèm',
                'verbose_name_plural': 'Tài liệu đính kèm',
            },
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên món')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị tính')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procure.procurementrecord')),
            ],
            options={
                'verbose_name': 'Danh sách món hàng',
                'verbose_name_plural': 'Danh sách món hàng',
            },
        ),
    ]
