# Generated by Django 5.2.4 on 2025-07-03 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Mã hồ sơ')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('desciption', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='procure/attachments/')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả tài liệu (nếu có)')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='procure.procurementrecord')),
            ],
        ),
    ]
