# Generated by Django 5.2.4 on 2025-08-06 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrecord',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày tạo'),
        ),
    ]
