# Generated by Django 5.2.4 on 2025-07-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procurementrecord',
            options={'ordering': ['code'], 'verbose_name': 'Hồ sơ', 'verbose_name_plural': 'Hồ sơ'},
        ),
    ]
