# Generated by Django 5.2.4 on 2025-07-07 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0002_alter_procurementrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tổng trị giá'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên món')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Đơn vị tính')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Đơn giá')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Đã thanh toán')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procure.procurementrecord')),
            ],
        ),
    ]
