# Generated by Django 5.2.4 on 2025-08-06 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0002_alter_procurementrecord_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày lập hồ sơ'),
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày tạo trên hệ thống'),
        ),
    ]
