# Generated by Django 5.2.4 on 2025-07-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0003_procurementrecord_total_cost_purchaseitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurchaseItem',
            new_name='PurchasedItem',
        ),
    ]
