# Generated by Django 5.2.4 on 2025-08-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0003_procurementrecord_date_recorded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementrecord',
            name='date_recorded',
        ),
        migrations.AlterField(
            model_name='procurementrecord',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
    ]
