# Generated by Django 5.2.4 on 2025-07-07 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0004_rename_purchaseitem_purchaseditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procurementrecord',
            old_name='desciption',
            new_name='description',
        ),
    ]
