# Generated by Django 5.2.4 on 2025-08-11 03:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procure', '0004_remove_procurementrecord_date_recorded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrecord',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày lập hồ sơ'),
        ),
    ]
